/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanManagerForm.Form;

import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author vongh
 */
public class GIAODIENCHINH_FORM extends javax.swing.JFrame {

    /**
     * Creates new form GIAODIENCHINH_FORM
     */
    public GIAODIENCHINH_FORM() {
        initComponents();
        LoadIcon();
        setLocationRelativeTo(null);
    }

    public void LoadIcon() {
        Image icon = Toolkit.getDefaultToolkit().getImage("\\QUANLYNHANSU_JAVA\\HumanManager\\src\\HumanManagerForm\\Icon\\emart-logo.jpg");
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMeNhanVien = new javax.swing.JMenuItem();
        jMePhongBan = new javax.swing.JMenuItem();
        JMeChucvu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMeChamcong = new javax.swing.JMenuItem();
        JMeBangLuong = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMeThue = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMeQLTK = new javax.swing.JMenuItem();
        jMeDangXuat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ NHÂN SỰ EMART");
        setAutoRequestFocus(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HumanManagerForm/Icon/emart-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(220, 30));

        jMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setText("  Quản lý");
        jMenu1.setAlignmentX(0.6F);
        jMenu1.setAlignmentY(0.7F);
        jMenu1.setBorderPainted(true);
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu1.setInheritsPopupMenu(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(70, 20));

        jMeNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMeNhanVien.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMeNhanVien.setText("Nhân viên");
        jMeNhanVien.setBorderPainted(true);
        jMeNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(jMeNhanVien);

        jMePhongBan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMePhongBan.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMePhongBan.setText("Phòng ban");
        jMePhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMePhongBanActionPerformed(evt);
            }
        });
        jMenu1.add(jMePhongBan);

        JMeChucvu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMeChucvu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JMeChucvu.setText("Chức vụ");
        JMeChucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMeChucvuActionPerformed(evt);
            }
        });
        jMenu1.add(JMeChucvu);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenuItem1.setText("Bằng cấp");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(153, 153, 153));
        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setText("  Lương");
        jMenu2.setBorderPainted(true);
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(65, 20));
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMeChamcong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMeChamcong.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMeChamcong.setText("Bảng chấm công");
        jMeChamcong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeChamcongActionPerformed(evt);
            }
        });
        jMenu2.add(jMeChamcong);

        JMeBangLuong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMeBangLuong.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JMeBangLuong.setText("Bảng lương");
        JMeBangLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMeBangLuongActionPerformed(evt);
            }
        });
        jMenu2.add(JMeBangLuong);

        jMenuBar1.add(jMenu2);

        jMenu5.setBackground(new java.awt.Color(153, 153, 153));
        jMenu5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu5.setText("  Thuế");
        jMenu5.setBorderPainted(true);
        jMenu5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(50, 20));

        jMeThue.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMeThue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMeThue.setText("Quản lý thuế TNCN");
        jMeThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeThueActionPerformed(evt);
            }
        });
        jMenu5.add(jMeThue);

        jMenuBar1.add(jMenu5);

        jMenu4.setBackground(new java.awt.Color(153, 153, 153));
        jMenu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu4.setText(" Tài Khoản");
        jMenu4.setBorderPainted(true);
        jMenu4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(80, 21));

        jMeQLTK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMeQLTK.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMeQLTK.setText("Quản lý tài khoản");
        jMeQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeQLTKActionPerformed(evt);
            }
        });
        jMenu4.add(jMeQLTK);

        jMeDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMeDangXuat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMeDangXuat.setText("Đăng xuất");
        jMeDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeDangXuatActionPerformed(evt);
            }
        });
        jMenu4.add(jMeDangXuat);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMeChucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMeChucvuActionPerformed
        // TODO add your handling code here:
        CHUCVU_FORM nv = new CHUCVU_FORM();
        nv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JMeChucvuActionPerformed

    private void jMeNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeNhanVienActionPerformed
        // TODO add your handling code here:
        NHANVIEN_FORM nv = new NHANVIEN_FORM();
        nv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMeNhanVienActionPerformed

    private void jMeDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeDangXuatActionPerformed
        // TODO add your handling code here:
        int thoat = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (thoat == JOptionPane.YES_OPTION) {
            DANGNHAP_FORM dn = new DANGNHAP_FORM();
            dn.setVisible(true);
            this.dispose();
        } else {
            return;
        }

    }//GEN-LAST:event_jMeDangXuatActionPerformed

    private void jMeQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeQLTKActionPerformed
        // TODO add your handling code here:
        TAIKHOAN_FORM tk = new TAIKHOAN_FORM();
        tk.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMeQLTKActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMeChamcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeChamcongActionPerformed
        // TODO add your handling code here:
        CHAMCONG_FORM fr = new CHAMCONG_FORM();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMeChamcongActionPerformed

    private void jMePhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMePhongBanActionPerformed
        // TODO add your handling code here:
        PHONGBAN_FORM frm = new PHONGBAN_FORM();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMePhongBanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        BANGCAP_FORM frm = new BANGCAP_FORM();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMeThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeThueActionPerformed
        // TODO add your handling code here:
        THUE_FORM frm = new THUE_FORM();
        frm.setVisible(true);
    }//GEN-LAST:event_jMeThueActionPerformed

    private void JMeBangLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMeBangLuongActionPerformed
        // TODO add your handling code here:
        BANGLUONG_FORM frm = new BANGLUONG_FORM();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JMeBangLuongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIAODIENCHINH_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIAODIENCHINH_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIAODIENCHINH_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIAODIENCHINH_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIAODIENCHINH_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMeBangLuong;
    private javax.swing.JMenuItem JMeChucvu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMeChamcong;
    private javax.swing.JMenuItem jMeDangXuat;
    private javax.swing.JMenuItem jMeNhanVien;
    private javax.swing.JMenuItem jMePhongBan;
    private javax.swing.JMenuItem jMeQLTK;
    private javax.swing.JMenuItem jMeThue;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
